### PR TITLE
Implement simple unit tests and refactor of main.py

### PR DESCRIPTION
**Pull request by andyg7**
- I added a simple test for loading the team data ("teams.json"), and the league data ("leagueproperties.py"). 
- used unittest tool
- to run tests there are two options: 
1) run the following from the root of the repository: python -m unittest discover tests
This will search the tests/ directory for ALL tests. This is recommended and best way in my opinion as it will always run every test in tests/ directory 
2)  run the following from the root of the repository:  python -m unittest tests.test_load_data
This will just run the tests in test_load_data.py

I wrote these tests just to get the ball rolling in terms of implementing unit tests. Let me know of any feedback! Thanks :)
Andy

### CODE REVIEW

**Comment by andyg7** [comment]
Hey guys,
I refactored the main.py as I mentioned in #111 here. Let me know of any feedback :)
Thanks so much,
Andy

**Comment by Saturn** [comment]
I like this.

Although in the test file is there a need to catch the exceptions?

```python
def test_load_team_data(self):
    raised = False
    try:
        load_json(TestLoadData.TEAMS_INFO_FILENAME)["teams"]
    except IOError:
        raised = True
    self.assertFalse(raised)
```

```python
def test_load_team_data(self):
    load_json(TestLoadData.TEAMS_INFO_FILENAME)["teams"]
```

I suppose in the case of an `IOError` the test runner will call the latter an `error` rather than a `failure`. But does it matter?

**Comment by andyg7** [comment]
Hi @Saturn thanks for the response. The idea of the simple test cases was just to check that the required files do indeed exist (e.g. leagueids.py and leagueproperties.py). If they don't exist then the load_json(file) function will throw an exception. So I figured we could test that the files do exist by checking that an exception is __not__ thrown; hence the try-catch. Does that make sense? However, the more I think about it the more I think maybe these tests aren't that helpful - if the those files don't exist then the test runner will almost assuredly crash anyways as so many other parts of the code base rely on them existing in the first place.

**Comment by Saturn** [comment]
I just didn't think it was totally necessary to wrap the individual tests in try except blocks.

If an `IOError` occurs just let it happen and the test runner will record it as an `error`.

And if you want to catch the exceptions within a test, you could do something like this instead.

```python
def test_load_team_data(self):
    try:
        load_json(TestLoadData.TEAMS_INFO_FILENAME)["teams"]
    except IOError:
        self.fail("File doesn't exist!")
```

Instead of creating flag variables. Just less typing.

**Comment by dfrt82** [comment]
At least the split-up of the main file looks good to me. Good work @andyg7 !

**Pull request merged**
