### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by thurask**
Since we replaced config.py with soccer-cli.ini, the readme should be updated to match.

### CODE REVIEW

**Comment by thurask** [comment]
And one more thing:

> #### Note:
Currently supports Linux, Mac OS X, NetBSD and FreeBSD.

I think Windows support (with colorama) is mature enough to be included. If we agree, I can add it to this PR.

**Comment by architv** [comment]
@thurask I don't have a windows machine. Does it run fine on yours? If yes, then add it.

**Comment by thurask** [comment]
Updated league code list.

Will add Windows, then it should be good to go.

**Comment by thurask** [comment]
OK, added.

**Comment by ueg1990** [comment]
@thurask thank you for verifying the project in Windows....you are now the GOTO guy for Windows of this project for many other developers :smile:

**Comment by architv** [comment]
Great @thurask ! Just one thing, could you squash all the commits into a single commit?

**Comment by thurask** [comment]
I take it auto-squash pull requests is off?

**Comment by architv** [comment]
Yes, forced auto-squash is off. It's up to the user if they want to do that.

I tried squashing your commits. See this https://github.com/architv/soccer-cli/commit/0f89a1eba96ab2faf742e7ad24f57d923aa920f5

**Comment by thurask** [comment]
Well, the content of the PR is in the repo in a nicely squashed commit, so I'm going to chalk the rest of it up to Git voodoo. ¯\_(ツ)_/¯

I'll go ahead and close this PR now.

**Pull request closed without merging**
