### PR TITLE
Clean up code for the Stdout writer.

### PR DESCRIPTION
**Pull request by carlosvargas**
* Removes code duplication for the different functions that print out the scores.
* Adds the league header to the live scores.
* Adds an Enum type for the different colors used.
* Removes the -1 score from the live scores. It just prints a "-" instead. 
```
================== Spanish Primera Division ==================

Getafe                     -  vs  -                    Malaga   6:30 PM UTC
````

* Right aligns the away teams to give some breathing room to the away goals.

```
============================= CL =============================

PSV Eindhoven              2  vs  1      Manchester United FC
```

### CODE REVIEW

**Comment by carlosvargas** [comment]
Btw, I kept getting the ImportError you guys were getting before.

```
> python .\soccer\main.py --live
Traceback (most recent call last):
  File ".\soccer\main.py", line 11, in <module>
    from soccer.exceptions import IncorrectParametersException
ImportError: No module named soccer.exceptions
```
I had to remove the `from exceptions import IncorrectParametersException` and do `import exceptions` then just reference `exceptions.IncorrectParametersException`.

**Comment by Saturn** [comment]
The exception importing error is due to the name clash that exceptions will have against the standard exceptions module.

If you run it like:
`python -m soccer.main --league LLIGA --standings`
You should not get an import error. Running it in this way will allow it to find `soccer.exceptions` no problem.

I will have a proper study of your PR a little bit later :+1:

**Comment by ueg1990** [comment]
looks great to me :smile: 

though i still dont get why the need to make the league_header a method esp when the name of the method also doesnt really match the implementation. lol

**Comment by carlosvargas** [comment]
@Saturn can't believe I forgot about that. Thanks.

@ueg1990 I made it a function since it's being used in 2 places (live scores and league scores) and didn't want to have duplicate code. What else could we name it? That function is just printing the league name in a "pretty" header.

**Comment by ueg1990** [comment]
oh i thought it was used in only one place...sorry....my bad

**Comment by carlosvargas** [comment]
haha np, there's a lot of code being moved, it would be easy to miss if you're not looking for it. I also considered adding that to the league standings, but wasn't sure if it's overkill since you're already specifying which league you want.

**Pull request merged**
