### PR TITLE
Allow user to use either env variable or config file to load API token

### PR DESCRIPTION
**Pull request by ueg1990**
In this change, i have included both ways to loading an API token.

Here is how the config.py file is expected to look like:

footballdata = {
    "SOCCER_CLI_API_TOKEN" : "xxxxxxx"
}

### CODE REVIEW

**Comment by Saturn** [comment]
This doesn't work for me. The exception never runs.

Also why is the config dict named `footballdata`?

Could we just do:
```python
from config import config

# ...
api_token = config.get('SOCCER_CLI_API_TOKEN')
```

`config.py`
```python
config = {
        "SOCCER_CLI_API_TOKEN": "38904ru093urw349rfphjwfiohewspf",
    }
```

**Comment by ueg1990** [comment]
I can do that. You should remove ur comment as it has ur API key :P

So do you have an env variable? if not, then maybe make sure the key is correct or re-run the setup.py script. I do 'python setup.py develop'

**Comment by Saturn** [comment]
I do not have an env variable set but I have the key set in config.py.

I just made up that API_KEY :smile:

**Comment by ueg1990** [comment]
hey, i think i found the reason why it didnt catch the exception...fixed it in latest commit

**Comment by Saturn** [comment]
Works for me now.

**Comment by thurask** [comment]
Maybe ConfigParser instead of a separate .py file?

Not sure if it's any better or worse.

**Comment by architv** [comment]
@ueg1990 Shouldn't there exception handler to import `config.py`. When a user installs the app for the forst time, it gives the error `ImportError: No module named config`. I'll add that in README anyway.

**Comment by ueg1990** [comment]
Thats true. In the REAME.md, mention both options of env variable and defining a config file (the config file steps are similar to authtoken.py).
You can show them an example of the config.py:
config = {
        "SOCCER_CLI_API_TOKEN": "38904ru093urw349rfphjwfiohewspf",
    }

**Pull request merged**
